name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.23.1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6.0.0
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: v2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
